### ISSUE TITLE
Where is QtWaitingSpinnerTest?

### ISSUE THREAD

**Issue by kainjow** [williamhallatt/QtWaitingSpinner#2]
I see it mentioned in the read me, but I don't see it in the source.

**Comment by kainjow** [comment]
Oops, wrong repo, but it looks like yours is where the files are. Forgot a pull request?

**Comment by williamhallatt** [comment]
It definitely was pulled back when I was still working on this (https://github.com/snowwlex/QtWaitingSpinner/commit/137aa190b433b558fe6da4ac57cf2f30f4a8ab00), the owner must have removed it since.  It has been quite a while since I last looked at/worked on this! :)
